apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dpl
spec:
  replicas: 2
  selector:
    matchLabels:
      part: backend
  template:
    metadata:
      labels:
        part: backend
    spec:
      containers:
        - name: app
          image: ivankhodyrev/bookstore-app:1.0
          ports:
            - containerPort: 5000
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DB_NAME
          - name: DB_HOST
            value: "pg-svc"
          