apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-state
spec:
  selector:
    matchLabels:
      part: db
  replicas: 1
  template:
    metadata:
      labels:
        part: db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-worker
      containers:
        - name: postgres-1
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DB_NAME
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DB_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DB_PASSWORD
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: local-storage
  volumeClaimTemplates:
    - metadata:
        name: local-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
