apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-configmap
data:
  nginx.conf: |
    server {
      listen 80;
      server_name _;
      
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;
      
      set $backend "http://app-svc:5000";

      location /static/ {
        alias /static/;
        expires 1y;
        add_header Cache-Control "public, immutable";
      }

      location / {
        proxy_pass $backend;
      }

      location /books {
        proxy_pass $backend/books;
      }

      location /create {
        proxy_pass $backend/create;
      }

      location /edit {
        proxy_pass $backend/edit;
      }

      location /delete {
        proxy_pass $backend/delete;
      }
    }