apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-dpl
  labels:
    prj: bookstoreapp
spec:
  replicas: 3
  selector:
    matchLabels:
      prj: bookstoreapp
      part: back
  template:
    metadata:
      labels:
        prj: bookstoreapp
        part: back
    spec:
      containers:
      - name: bookstore-app-01
        image: ivankhodyrev/bookstore-app:1.0
        ports:
          - containerPort: 5000